export const USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS';
export const USER_AUTH_ERROR = 'USER_AUTH_ERROR';

export const UISTATE_PROMISE_LOADING = 'UISTATE_PROMISE_LOADING'
export const UISTATE_PROMISE_SUCCESS = 'UISTATE_PROMISE_SUCCESS'
export const UISTATE_PROMISE_ERROR = 'UISTATE_PROMISE_ERROR'
export const UISTATE_PROMISE_SUCCESS_RESET = 'UISTATE_PROMISE_SUCCESS_RESET'
